spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver	
    #url: jdbc:mysql://localhost:3306/high?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8
    #执行SQL分析打印	
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/high?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

logging:
  level:
    root: warn
    com.mp.dao: trace
  pattern:
    console: '%p%m%n'
    
mybatis-plus:
   global-config:
      db-config:
         logic-not-delete-value: 0
         logic-delete-value: 1
      #3.1.1版本一下的sql过滤  对应mappert sql语句的@SqlParser(filter=true)注解 
      sql-parser-cache: true      