spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver		
    url: jdbc:mysql://localhost:3306/mp?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

logging:
  level:
    root: warn
    com.mp.dao: trace
  pattern:
    console: '%p%m%n'
    
mybatis-plus:
  mapper-locations:
  - com/mp/mapper/*
  #配置全局id主键策略    
  global-config:
    db-config:
      id-type: auto
      #设置字段在sql语句中的生成策略 默认字段为null时不加入sql语句
      #ignored:都会加入 not-empty:为null或空不会加入 not-null:为空不加入       
      #field-strategy: ignored
      #全局表名配置
      #table-prefix:  mp_
  #配置config文件
  #config-locations: classpath:mybatis-config.xml
  #别名
  type-aliases-package: com.mp.entity
  #configuration与config-locations不能同时定义否则报错
  configuration:
    map-underscore-to-camel-case: true
    